TOP=../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

#----------------------------------------------------
# Create and install (or just install) into <top>/db
# databases, templates, substitutions like this
DB += ecat2ek1101.db
DB += ecat2el2124.db
DB += ecat2el3202.db
DB += ecat2el4102.db
DB += ecat2el4134.db
DB += ecat2el1014.db
DB += ecat2el2502.db
DB += ecat2el3214.db
DB += ecat2el4104.db
DB += ecat2el2004.db
DB += ecat2el3164.db
DB += ecat2el3602.db
DB += ecat2el4122.db
DB += ecat2ekxxxxID.template
DB += ecat2el20xxel2124DO.template
DB += ecat2el316x.template
DB += ecat2el321x.template
DB += ecat2el41xx.template
DB += ecat2slave.template
DB += ecat2el10xxel11xxDI.template
DB += ecat2el250x.template
DB += ecat2el3208.template
DB += ecat2el360xel320x.template
DB += ecat2master.template


#USR_DBFLAGS += -I . -I .. -I $(INSTALL_LOCATION)/db

#----------------------------------------------------
# If <anyname>.db template is not named <anyname>*.template add
# <anyname>_template = <templatename>

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE

